# Generated by Django 4.1.7 on 2023-03-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitfiles',
            name='document',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
