# Generated by Django 4.1.7 on 2023-03-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_permitfiles_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='project_address',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='project_documents',
        ),
        migrations.DeleteModel(
            name='PermitFiles',
        ),
    ]
